### ISSUE TITLE
Upload cleanup upon failure deletes unrelated data 

### ISSUE THREAD

**Issue by enricorotundo** [mtth/hdfs#136]
## Problem
The [client's upload function](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.upload) has a `True` cleanup argument by default. If the upload fails, it will remove the entire `hdfs_path` and not only the attempted uploaded files as described in the docs.

## Reproduce

Run:
```CLIENT.upload(hdfs_path="/user/blabla/data/raw", local_path="data/raw/", n_threads=1)```

This failed with some error

```
ERROR	Error while uploading. Attempting cleanup.
...
```

The side effect is that it completely removed the `hdfs_path` folder in hdfs.

Env. specs: `hdfs==2.2.2` in `Python 3.6.7`.

**Comment by mtth** [comment]
If the destination folder already exists, `upload` will write to a temporary directory instead of the final destination (and deletes only that one during cleanup). Unless you are concurrently uploading files to the destination folder, this should guard against unexpected deletions. Would you be able to provide a reproducible example where the current behavior isn't right?
