### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by mtth** [mtth/hdfs#203]
Follow up to #192 (see https://github.com/mtth/hdfs/pull/192#issuecomment-1671591466).

**Comment by musicinmybrain** [comment]
I think I am going to work around this in the Fedora package by adding [`zombie-imp`](https://pypi.org/project/zombie-imp/) to `install_requires` so that, when `from importlib import load_source` raises an `ImportError` on Python 3.12, the `from imp import load_source` fallback works. The `zombie-imp` project is plastered with warnings not to use it, so this not a good long- or even medium-term solution. I’m not sure I will have time to dig into finding the correct way to replace `load_source` in this project, though.

**Comment by mtth** [comment]
FYI just noticed Python 3.12's [release notes](https://docs.python.org/3.12/whatsnew/3.12.html) have a section on replacing `imp.load_source` (found via https://github.com/python/cpython/issues/104212#issuecomment-1606129262).

**Comment by musicinmybrain** [comment]
Nice, that’s both new and useful. I’m happy to try it out and offer a PR. I don’t really have a high-level understanding of the autoload system to which this belongs; do we want the module cached in `sys.modules` or not?

**Comment by mtth** [comment]
> do we want the module cached in sys.modules or not?

Not an expert either but leaning towards caching to avoid potentially odd behaviors since [client classes are cached](https://github.com/mtth/hdfs/blob/da512546112ffc6bd9391ceee7b0fca79adb6a6b/hdfs/client.py#L150) and executing the module multiple times might otherwise lead to race conditions.
