### ISSUE TITLE
No way to send kwargs to the _Request objects

### ISSUE THREAD

**Issue by laserson** [mtth/hdfs#22]
I am trying to connect to a namenode on a kerberized cluster but am having problems because of an invalid certificate authority.  It would be great if I could provide `verify=False` to the `_Request` objects, perhaps on a per-session basis.

**Comment by laserson** [comment]
Actually, only just realized the `params` gets passed through.  Will close this if it solves my issue.

**Comment by laserson** [comment]
Ok, `params` does NOT solve my problem.  Looks like it adds parameters that get URL-encoded.  I want to be able to inject options to the `request` call itself.  For example, in https://github.com/kennethreitz/requests/blob/master/requests/api.py#L69 I want to be able to add things to `kwargs`.

**Comment by mtth** [comment]
Good point. Thanks for the pull request, I was actually just working on a fix. Rather than expose all `resquest` `kwargs`, I'd rather add just those that make sense (for now `verify` and `cert`): this is more easily supported with aliases, is more consistent with the current `timeout` parameter, and prevents failures (e.g. passing `stream` would cause strange effects).

Let me know if this doesn't solve your use-case, we'll see how to best merge your pull request. For now, I just released a new updated version (`1.1.2`).

**Comment by laserson** [comment]
I was trying to use `verify`, so that's sufficient for me now.  Thanks!

**Comment by laserson** [comment]
(`rq_kwargs` is really ugly, too)

**Comment by mtth** [comment]
Great :). Just realized I forgot to update the extra calls in `write` and `append`, will release an updated version.

**Comment by mtth** [comment]
@laserson - fixed in `1.1.3`, apologies for the split release.
