### ISSUE TITLE
Permission denied user: dr.who ACCESS:write unable to write to hdfs

### ISSUE THREAD

**Issue by swaapnika-guntaka** [mtth/hdfs#85]
I'm using the HDFS cli to write some data as kafka user.  User permissions on the HDFS location are as below.
```
hdfs dfs -ls /
drwxr_xr_x kafka hdfs  /test
```
When I manually try to create a file using below command it runs fine as kafka user which means the kafka user has write permissions on the directory I'm trying to write. 
`hdfs dfs -mkdir /test/write_test`

But when I try to create file using the HDFS Cli in the script it says User:dr.who doesnt have permission to write. I've logged in as kafka user.` whoami shows kafka` 

**the problem is the code is not picking/recognizing the current user**
This is my code.
`#!/usr/bin/env python

from hdfs.client import Client
from hdfs.util import HdfsError

from json import dump 

def main():
		client = Client('http://host.domain.name.com:50070', root=None, proxy=None, timeout=None, session=None)
		records = [ {'name': 'foo', 'weight': 1}, {'name': 'bar', 'weight': 2},]
		try:
			with client.write('/test/file2', encoding='utf-8') as writer:
				dump(records, writer)
		except HdfsError as e:
			print("HdfsError" )
		content = client.content('/test/file2', strict=True)
		if content is not None:
			print("Data written")
		else:
			print("No data")

if __name__ == "__main__":
	main()
`
![kafka_user_hdfs_cli](https://user-images.githubusercontent.com/18042968/33338833-211ba034-d42c-11e7-84ba-60450bbd24b5.png)

**Comment by wumingpu** [comment]
I also meet this question, you can try to use the 
client = InsecureClient(hdfs_url, user='kafka') instead of 
client = Client(hdfs_url, root=None, proxy=None, timeout=None, session=None)

The parameter user in InsecureClient() is that you can assign a user to operate the HDFS.

I refer the contents as below:
https://stackoverflow.com/questions/18210547/append-operation-in-hadoop-webhdfs-client 
https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.InsecureClient

**Comment by mtth** [comment]
That's correct; you'll need to specify a user when creating the client and `InsecureClient` provides a convenient way to do so (it's a lightweight wrapper around the base `Client` which sets the right session parameter).
